blank_issues_enabled: false
contact_links:
  - name: 🚀 Priority Support
    url: https://github.com/sponsors/privatenumber/
    about: Need help? Get prioritized help for all your questions and issues
